# load /etc/profile in compatibility mode
# emulate sh -c 'source /etc/profile'

if [ "$HOST" = "T470-Kubuntu" ]; then
    ## fix phantom middle click and scroll
    xinput set-button-map "TPPS/2 IBM TrackPoint" 1 0 3
    xinput set-prop "TPPS/2 IBM TrackPoint" "libinput Button Scrolling Button" 0
fi

# load same environment variables as bash and X
source "$HOME/.env"
